### ISSUE TITLE
Analysis: previous actions in trust ratings

### ISSUE THREAD

**Issue by psokolhessner** [sokolhessnerlab/bst#2]
Analyses of trust decisions (in the Trust Game) indicate effects of previous actions on subsequent actions. No sequential effects analyses have been performed on trust perception (Trust Ratings). 

**Describe the solution you'd like**

- [x] Create vector of trust ratings shifted forward one trial (i.e. trust ratings 1:T are shifted forward to 2:T+1; called `prevRating`). Ensure every participant's trial 1 value is 0.
- [x] As in sequential effects analyses of trust decisions, include `prevRating` in a) simple regressions, and b) complex full-featured regression including acute & chronic stress. 
- [x] Update main summary document w/ brief summary of findings.

**Comment by EvrimBaykal** [comment]
This checklist looks completed, and we are working previous trial trust analysis in the new script.  Closing this issue!
