### ISSUE TITLE
Reorganize Survey Data

### ISSUE THREAD

**Issue by EvrimBaykal** [sokolhessnerlab/bst#6]
- [x] Move explicit attitudes survey scoring file (CM, IMS-EMS, MRS, SRS) from /scannedpaperdocs/ to /Current_Dataframes/ directory
- [x] rename readme_scoring_survey_data.md
- [x] fill out contents of readme_scoring_survey_data.md with references and any helpful method info
- [x] establish final .csv current dataframe names 
- [x] update setup script with finalized dataframe names

**Comment by EvrimBaykal** [comment]
Update 6-29-2024: readme_scoring_survey has been created and readme_data_compiling has been renamed/updated.

**Comment by EvrimBaykal** [comment]
@psokolhessner The current df names are now documented in a readme in the shlab server.  Do you recommend that we make a .csv of those names, too?

**Comment by psokolhessner** [comment]
I think a readme would be sufficient, @EvrimBaykal?

**Comment by EvrimBaykal** [comment]
Agreed @psokolhessner !  I'm closing this issue!
