### ISSUE TITLE
Do regression on all cortisol samples by sample number, day, and stressor

### ISSUE THREAD

**Issue by psokolhessner** [sokolhessnerlab/bst#8]
Assess cortisol samples (using flat array) using regression to test whether Sample Number, Day, and Stressor drive cortisol values. 

Something like: 
`model_cort_samples = lmer(cortisol_mean_nmol_to_l ~ 1 + sample + day + control0stress1 + (1 | subjectID), data = cort)`

**Notes:**
- `sample` may be used as a linear variable (1, 2, 3, 4), or FACTOR (i.e. first, second, third, and fourth); first will look for linear patterns like decreases over time, but the 2nd will allow for nonlinearities. 
- There might be an argument to made for interacting e.g. `control0stress` with `day` or with `sample`, but think carefully about how that'll work. 
- As a complementary analysis, could do *four regressions* - one for each sample (i.e. a regression only on sample 1 values). Wouldn't be able to do hierarchical regression with this as too few datapoints/person (i.e. just 2 at most, and only 1 in some cases). At a certain point, this approach is identical to the factor-based approach mentioned above. 

Line 132 or so in the [`stress_analysis.R`](https://github.com/sokolhessnerlab/bst/blob/main/bst_analysis/bst_scripts/stress_analysis.R) file could be a good place to do this.

**Comment by EvrimBaykal** [comment]
@psokolhessner I am using "apply" to calculate the means/sd of the cort_mtx.  Are the columns in the cort_mtx fron the day or stress boolean?  I believe this is by day but wanted to double-check.
```
# Means of each sample by day across participants (subject-level)
cort_means_by_sample_and_day = apply(cort_mtx, c(1, 2), mean, na.rm = TRUE)
#         [,1]     [,2]
# [1,] 1.541000 2.126429
# [2,] 1.735957 2.004500
# [3,] 3.026596 2.570250
# [4,] 1.823404 1.931538
#Q: Why are trajectories for Day 1 and Day 2 substantially different?

# Standard deviations of each sample by day across participants (subject-level)
cort_sd_by_sample_and_day = apply(cort_mtx, c(1, 2), sd, na.rm = TRUE)
#         [,1]     [,2]
# [1,] 1.202253 3.321143
# [2,] 1.278518 2.890279
# [3,] 3.517918 2.768810
# [4,] 1.346669 1.690566

```

**Comment by psokolhessner** [comment]
Whenever you have a Q like this @EvrimBaykal, use the creation code to find the answer. It's a good habit overall, and it connects you better to the code we're using. See [this line](https://github.com/sokolhessnerlab/bst/blob/5b5a381ac561b9e1d16290fafbc00211a618f0ed/bst_analysis/bst_scripts/setup_data.R#L149) and those that immediately follow.

What you quoted above is by sample (i.e. first, second, third, or fourth sample) & by day, across people.

**Comment by EvrimBaykal** [comment]
@psokolhessner Great. Thanks!  I was confused b/c these lines were in the loop that I believe have not yet been added to the matrix?

```
tmp_day1 = as.numeric(bathOrder$Day.1[bathOrder$subjectID == subjID] == 'STRESS') # gives 1 if stress, 0 if control
tmp_day2 = as.numeric(bathOrder$Day.2[bathOrder$subjectID == subjID] == 'STRESS') 
```

**Comment by psokolhessner** [comment]
In what loop @EvrimBaykal? They're not in the loop to create the `cort_mtx` object...

**Comment by EvrimBaykal** [comment]
@psokolhessner I see. Yes, the lines are outside the cort_mtx object and are part of a new loop creating the stress condition.  Thanks!

> 185

**Comment by psokolhessner** [comment]
Cool, yeah. They're just meant to add the stress condition on a per-sample basis to the `cort` object for use in regressions (i.e. to facilitate the regression described in this issue!). 

Note that we _could_ also make the `cort_mtx` object a sample x day x condition x subject object (4 x 2 x 2 x N). There would be a bunch of blanks in there (b/c everyone has only one condition on only one day), but it might be a nice way of creating _one_ object that allows us to ask questions about sample number, or day, or condition...

Thoughts @EvrimBaykal?

**Comment by EvrimBaykal** [comment]
Oh, yes!  Making a 4 x 2 x 2 x N matrix would be great for subject-level descriptive analysis (and beyond) and data visualization of sample x day x condition.  NAs should not pose a big issue! @psokolhessner

**Comment by psokolhessner** [comment]
Totally - we're already handling NAs! 

If you want to do this, probably just alter the creation code for `cort_mtx` to...
- [x] Identify the condition number associated with a given sample
- [x] place that sample & day & subject's sample in the correct _condition_ location

Let me know if you want to strategize about how to accomplish that in the `R` code.

**Comment by EvrimBaykal** [comment]
@psokolhessner Did you want to add anything else to this issue?  If not, I think we can close it!  👍🏽

**Comment by psokolhessner** [comment]
Yup agreed with you @EvrimBaykal that this one is done. Closing now!

**Comment by EvrimBaykal** [comment]
Thanks, @psokolhessner !
